#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
   path: /
   controller: App\Controller\TestController::index

test:
   path: /test/{age<\d+>?0}
   controller: App\Controller\TestController::test
   #this can be directly replaced in the path parrams declaration like up {age? default_value}
   #defaults:
   #   age: 0
   #########################
   #we can refactor this requirement using the <> expression inside the path parameter like up
   # {age< condition regex here >}
   #requirements:
   #   age: \d+
   #### TIP #####
   # you can use the long expressions in big projects to be more readable if you like
   ####